### ISSUE TITLE
Validate if Gluu SCIM 2.0 conform spec

### ISSUE THREAD

**Issue by yurem** [GluuFederation/SCIM-Client#13]
It's latest SCIM 2.0 https://tools.ietf.org/html/rfc7643

**Comment by yurem** [comment]
There is no information in spec about:
https://github.com/GluuFederation/oxTrust/blob/master/scim/src/main/java/org/gluu/oxtrust/model/scim2/Meta.java#L34

**Comment by uboznikov** [comment]
Add filtering, sorting, and pagination

https://tools.ietf.org/html/rfc7644#section-3.4.1

**Comment by jgomer2001** [comment]
Current implementation is generating **meta** dates conforming *xsd:dateTime* so we are compliant in this regard. See section 2.3.5 RFC 7643
