### ISSUE TITLE
SCIM 2.0 should support custom attributes per RFC 7643

### ISSUE THREAD

**Issue by yurem** [GluuFederation/SCIM-Client#14]
There are 2 places in next class with message:
 NOTE : WRITE CODE FOR THIS

1) https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/util/CopyUtils2.java#L369
2) https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/util/CopyUtils2.java#L609

This sample user we can use as example:
https://tools.ietf.org/html/rfc7643#page-35

There is no attributes in meta section. I believe it's better to add customAttributes to main user section

**Comment by yurem** [comment]
Michael Schwartz: https://tools.ietf.org/html/rfc7643

 "In addition to the minimal core schema, this document also specifies a standardized means by which service providers may extend schemas to define new resources and attributes in both standardized and service-provider-specific cases."
So Shekhar needs to read this doc, and align with the suggested mechanism

Yuriy Movchan: In SCIM 1.0 we invited customAttributes list. Shekhar can just reuse same code to prepare quick fix which compatible with customer json. After that he can start work on solution which compatile with SCIM 2.0 spec

Michael Schwartz: it doesn't pay to implement a non-SCIM 2.0 solution.
Its better to do it right the first time.

**Comment by uboznikov** [comment]
This constitutes two major tracks:

1. Expose the schema of the custom attributes/extensions in "/Schemas" endpoint to enable clients to discover and parse the custom attributes/extensions.
2. Include handling of the actual custom attributes/extensions in the Resources endpoints. As of now add handling in "/Users" endpoint only.

**Comment by shekhar16** [comment]
I already fixed as client raised issue for this on gluu support.custom attributes are added.
