### ISSUE TITLE
Enable UserExtensionsJsonTest/UserExtensionsPersonTest tests

### ISSUE THREAD

**Issue by yurem** [GluuFederation/SCIM-Client#15]
I added next [test data](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/test/scim-client/data/scim-test-data.ldif) to CE to allow enable these tests: UserExtensionsJsonTest/UserExtensionsPersonTest 

Please move: CREATEJSON/UPDATEJSON to https://github.com/GluuFederation/SCIM-Client/blob/master/src/test/resources/testng.properties

It's easier to maintain JSON in properties file than in code.

**Comment by uboznikov** [comment]
Committed [75a9080095ef4c986dafeafb2e1e2d1cc3925fd4](https://github.com/GluuFederation/SCIM-Client/commit/75a9080095ef4c986dafeafb2e1e2d1cc3925fd4)
