### ISSUE TITLE
User tests for Country fail due to "Azerbaijan" not being an ISO 3166-1 alpha-2 country code

### ISSUE THREAD

**Issue by cjqed** [GluuFederation/SCIM-Client#18]
There are many places that the SCIM client tests set the country to names of countries:
https://github.com/GluuFederation/SCIM-Client/search?utf8=%E2%9C%93&q=setCountry

But according to the SCIM 2.0 spec here: https://tools.ietf.org/html/rfc7643 , the country attribute on a user:

> When specified, the value MUST be in ISO 3166-1 "alpha-2" code format [ISO3166]; e.g., the United States and Sweden are "US" and "SE", respectively.

When testing with compliant servers, this causes the scim client tests to fail.

**Comment by uboznikov** [comment]
Thank you for this find; we have been following the examples from the spec and "USA" was being used.

> When testing with compliant servers, this causes the scim client tests to fail.

We are interested how you were able to integrate SCIM-Client with other SCIM servers, could you please elaborate more and describe the steps involved? Thanks.

**Comment by jgomer2001** [comment]
> Thank you for this find; we have been following the examples from the spec and "USA" was being used.

Right, the spec examples are innacurate: *US* should be used

> When testing with compliant servers, this causes the scim client tests to fail.

Any update on this... pretty important for us

**Comment by cjqed** [comment]
It's been a year so I don't remember the exact steps, sorry. The gist is that we have a SCIM 2.0 server that we were trying to test with various SCIM clients we found through the web, and so I remember pulling this repo, changing some things in the client test code to point to my local SCIM server, and running tests. Everything was fine except when creating / modifying users that had countries set to things like "Russia" or "Azerbaijan" instead of "RU" or "AZ" respectively, our SCIM server returned a 400 with the error those aren't ISO 3166-1 alpha-2 country codes. As per the spec they do need to be, so the client tests aren't compliant with the spec.

Does that make sense?

**Comment by jgomer2001** [comment]
Absolutely! ... have to fix

**Comment by jgomer2001** [comment]
https://github.com/GluuFederation/SCIM-Client/blob/master/src/test/java/gluu/scim2/client/TestModeTests.java#L48
