### ISSUE TITLE
'null' middleName should represent as 'null' or space

### ISSUE THREAD

**Issue by mzico** [GluuFederation/SCIM-Client#21]
https://support.gluu.org/identity-management/4084/person-attribute-not-updating-with-null-or-values/

**Comment by mzico** [comment]
@jgomer2001 : Not pushing but any update on this? The associated ticket is becoming one of the 'longest' ticket of our support portal history. :-)

**Comment by jgomer2001** [comment]
@mzico Sorry for the delay
