### ISSUE TITLE
UMA 2 : Update RPT Policy Script and obtain correct token_claims for back-channel call

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/SCIM-Client#22]
I already adapted code to UMA 2 here.
https://github.com/GluuFederation/SCIM-Client/commit/2d9cb6f8f1c62f14c54af17e6018c7d2cf6c1ce8
and here https://github.com/GluuFederation/SCIM-Client/commit/bb2c338e3ebd7d0c401a2ffe37a7f6943b761763

But it needs further work to have correct claims token for correct behavior.
oxauth 3.1.0 supports only UMA 2 (no UMA 1.0.1 anymore),
Spec: https://docs.kantarainitiative.org/uma/ed/oauth-uma-grant-2.0-04.html#rfc.section.3.3.1
Since it is back-channel call (no user interaction) claimToken must contain all claims that are used in RPT Authorization Policy Script. In our case cliamsToken is idToken. Please obtain id_token with all claims that are required by RPT script.

Fix must be in those classes
- provided correct `claims_token`  https://github.com/GluuFederation/SCIM-Client/blob/2d9cb6f8f1c62f14c54af17e6018c7d2cf6c1ce8/src/main/java/gluu/scim/client/auth/UmaScimClientImpl.java#L190-190
- access_token for RPT Token endpoint must be correctly obtained https://github.com/GluuFederation/SCIM-Client/blob/bb2c338e3ebd7d0c401a2ffe37a7f6943b761763/src/main/java/gluu/scim2/client/UmaScimClient.java#L140-140
- provided correct `claims_token` https://github.com/GluuFederation/SCIM-Client/blob/bb2c338e3ebd7d0c401a2ffe37a7f6943b761763/src/main/java/gluu/scim2/client/UmaScimClient.java#L164-164

**Comment by jgomer2001** [comment]
For this scenario we have:
* Client: SCIM-Client
* Resource server: oxTrust+oxAuth
* Authz Server: oxAuth

Admin can be considered resource owner. Also, there is no human requesting party (no user-facing interaction taking place). 

Thus, as no authenticated end-users are involved here, there is no presence of an id_token at all. Indeed, SCIM-client does not really need presenting any kind of claims. They are optional in the UMA spec also.

So authorization can be determined as in UMA1.0.1 interception script: it was checked if a certain pre-registered client was being involved, the so called "SCIM requesting party client". Hence, claims pushing or interactive claims gathering is out of the question.

Current sample interception script is suitable in a setting where an end-user is involved in the process, e.g. one can check if certain attributes have certain values and then decide whether to authorize or not.

**Comment by jgomer2001** [comment]
https://github.com/GluuFederation/SCIM-Client/commit/2416fe1f33b6dcfff276fa153aaba9b7ffbfcaa4

`UmaRptPolicy_SCIM.py` custom script was added:
https://github.com/GluuFederation/oxAuth/commit/ed9ce5238ea7b9f6ece7ca834162d07a222f80c0

**Comment by jgomer2001** [comment]
https://github.com/GluuFederation/SCIM-Client/tree/uma2_upgrade
https://github.com/GluuFederation/oxTrust/tree/uma2_upgrade

**Comment by jgomer2001** [comment]
Python script was fixed https://github.com/GluuFederation/oxAuth/commit/de8055eb8352900460a83a516ded43c42febe84c
