### ISSUE TITLE
Duplicity in SCIM v1.0 and SCIM v2.0 code

### ISSUE THREAD

**Issue by yurem** [GluuFederation/SCIM-Client#5]
There are a loot of duplicity in SCIM v1 and v2 code. We need to merge them to simplify code support.

**Comment by willow9886** [comment]
@yurem Perhaps we should simply remove SCIM 1 support in the next version..

**Comment by yurem** [comment]
We can close this issue. I see good tendency of writing simpler and reusable methods now
