### ISSUE TITLE
Migrate  to com.fasterxml jackson serialization library

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/SCIM-Client#61]
Current scim-client and server implementation (in oxTrust) are using older `org.codehaus` jackson library for serialization/deserialization processes (json <--> java )

We must take steps to migrate code to a more recent version of jackson lib (aka `com.fasterxml`).

We need to analyze the impact of moving these dependencies and determine which maven subprojects need to be altered.

This [support ticket](https://support.gluu.org/identity-management/4872/scim-client-jackson-provider-issue/) gives more context of the problem.

**Comment by jgomer2001** [comment]
This [ticket](https://support.gluu.org/identity-management/5579/scim-create-user-error-extension-customattributes-not-recognized/) also gives info.

We need to consider removing deprecated `resteasy-jackson-provider` in favor of new `resteasy-jackson2-provider` module

**Comment by jgomer2001** [comment]
Related https://github.com/GluuFederation/oxAuth/issues/811

**Comment by syntrydy** [comment]
@jgomer2001 I did that last week for all oxTrust modules.
