### ISSUE TITLE
Gluu3.1.2 QA - User status not ACTIVE when created using SCIM Client

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/SCIM-Client#63]
Create a User using SCIM Client. 
Expected - User Status should be Active.
Actual - Status attribute is missing
![image](https://user-images.githubusercontent.com/21104811/34367254-37dbbc38-eace-11e7-8a05-50c54226844e.png)

**Comment by jgomer2001** [comment]
> Expected - User Status should be Active.

Conversely, user should be inactive.

In your creation request you should pass `active` property (true or false) and this will make `gluuStatus` LDAP atribute be set properly.

When `active` is missing in the request, by default user gets inactive status: I [added this behavior](https://github.com/GluuFederation/oxTrust/blob/6c1bf00cd018bbbce0bb24a925d3fdd2a8e54731/server/src/main/java/org/gluu/oxtrust/util/CopyUtils2.java#L1405) on Dec 26th.

Usage example:

```
user.setActive(true);
```
