### ISSUE TITLE
SCIM client stop work after few minutes

### ISSUE THREAD

**Issue by yurem** [GluuFederation/SCIM-Client#66]
In apps which uses SCIM we create SCIM Client on app load and reuse it later.
In new 3.1.2 there is no method which checks AAT, RPT expiration. As result SCIM log error:
```
2018-01-05 15:44:47,293 ERROR [qtp477289012-14] [org.gluu.oxtrust.service.uma.UmaPermissionService] (UmaPermissionService.java:115) - Status response for RPT token: 'c7f6629d-5f21-4fad-ba9f-ad1e63db9fc1_C6B9.73BB.3226.A7E7.5BD2.B181.9861.8A77' is invalid
```

**Comment by yurem** [comment]
In 3.0.2 this method exists:
https://github.com/GluuFederation/SCIM-Client/blob/version_3.0.2/src/main/java/gluu/scim2/client/auth/UmaScim2ClientImpl.java#L114

**Comment by jgomer2001** [comment]
@yurem 
... trying to programmatically get expiration time of RPT with no success:

**Attempt 1:**
```
Jwt jwt=org.xdi.oxauth.model.jwt.Jwt.parse(rpt);
Long exp=jwt.getClaims().getClaimAsLong(JwtClaimName.EXPIRATION_TIME);
```

output: 
```
org.xdi.oxauth.model.exception.InvalidJwtException: Invalid JWT format.
        at org.xdi.oxauth.model.jwt.Jwt.parse(Jwt.java:73)
        at gluu.scim2.client.UmaScimClient.getAuthorizedRpt(UmaScimClient.java:174)
```

... a string like `c7f6629d-5f21-4fad-ba9f-ad1e63db9fc1_C6B9.73BB.3226.A7E7.5BD2.B181.9861.8A77` doesn't look like a JWT


**Attempt 2** (using [token introspection](https://github.com/GluuFederation/oxAuth/blob/version_3.1.2/Client/src/test/java/org/xdi/oxauth/ws/rs/IntrospectionWsHttpTest.java)):

```
Token authorization = UmaClient.requestPat("https://localhost:8443/oxauth/restv1/token",
                        umaAatClientJksPath, umaAatClientJksPassword, umaAatClientId, umaAatClientKeyId);
IntrospectionService introspectionService = ClientFactory.instance().createIntrospectionService("https://localhost:8443/oxauth/restv1/introspection");
IntrospectionResponse introspectionResponse=introspectionService.introspectToken("Bearer " + authorization.getAccessToken(), rpt);
```
but oxauth log shows

```
TRACE IntrospectionWebService.java:69- Introspect token, authorization: Bearer 6dcf5291-7913-436f-b6b7-f763d674efb2, token to introsppect: 75a7e6c1-9c97-4000-be1c-8d2d132f1fa1_DA58.76EB.B1A0.742E.5996.558B.9601.E6F1, tokenTypeHint:
ERROR IntrospectionWebService.java:103- Access token is not valid. Valid: true, isPat:false
```


**Attempt 3** (same as 2 but getting token this way):

```
tokenRequest = UmaScimClient.getAuthorizationTokerRequest(umaMetadata);
TokenClient tokenClient = new TokenClient("https://localhost:8443/oxauth/restv1/token");
tokenClient.setRequest(tokenRequest);
TokenResponse tokenResponse=tokenClient.exec(); 
```

got the same error


**Attempt 4**

I added scope *uma_protection* to OIDC client used by SCIM-client, which I thing is wrong and tried strategy 2, and got null expiration time.

oxauth log showing

```
07:36 ERROR introspection.ws.rs.IntrospectionWebService IntrospectionWebService.java:99- Failed to find grant for access_token: 2f519508-61d9-4b1d-a749-6a85b4d22645_73BB.0E83.0072.0BC1.8CD5.07DC.1168.94AC
```

Any idea? as a last resort we can compute time based on hardcoded time of one hour (oxauth's default for RTPs)

**Comment by jgomer2001** [comment]
... or add expiration field to `UmaTokenResponse` in oxauth-model so we can send the value back to client here: https://github.com/GluuFederation/oxAuth/blob/version_3.1.2/Server/src/main/java/org/xdi/oxauth/uma/service/UmaTokenService.java#L121-L125

**Comment by yurem** [comment]
@jgomer2001 You right this new API doesn't return expiration time. @yuriyz  Can you add expiration time to UMATokenService enpoint?

**Comment by yurem** [comment]
I added expiration time: https://github.com/GluuFederation/oxAuth/commit/134cee4ebddb7fe1ef0879f0318fc804e0e12889
Now SCIM Client can use it to re-issue new token on expiration.

**Comment by yuriyz** [comment]
There is introspection endpoint for RPT which returns expiration time as well as permissions:

https://github.com/GluuFederation/oxAuth/blob/version_3.1.2/Client/src/main/java/org/xdi/oxauth/client/uma/UmaRptIntrospectionService.java#L26-26

**Comment by yuriyz** [comment]
Spec points:
https://docs.kantarainitiative.org/uma/wg/oauth-uma-grant-2.0-09.html#rfc.section.3.3.5
https://docs.kantarainitiative.org/uma/wg/oauth-uma-federated-authz-2.0-09.html#rfc.section.5.1

**Comment by jgomer2001** [comment]
No need to change client, just made server side code return 401 with header `WWW-Authenticate`
