### ISSUE TITLE
Allow searching with startindex values higher than max_count

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/SCIM-Client#69]
Problem context found in this [ticket](https://support.gluu.org/identity-management/5241/user-search-field-startindex-limits-number-of-results-returned/).

**Comment by jgomer2001** [comment]
The searching functionality was not implemented propertly. It just run a search capped at `max_count` items, and then took the slice `[startCount - 1, startCount - 1 + count)`

Proper solution is to scroll through different LDAP result pages in a way that `max_count` does not impose any restriction on where the required results start at, thus avoiding increasing `max_count` to impractical high values.

**Comment by jgomer2001** [comment]
In this [issue](https://github.com/GluuFederation/oxTrust/issues/876) `max_count` had been increased. With the current fix, there is no need for that. I have reverted again to 200.

`max_count` should be set to any value that users consider could be the upper bound for the `count` parameter of SCIM searches. In practice this may be less than 200 actually.
	
https://github.com/GluuFederation/community-edition-setup/commit/ed44ad334abb5db1ca0fa01adc18bb3415189821
https://github.com/GluuFederation/community-edition-setup/commit/230db733a961ecec1d826eb2a65439a1f32ff83d
