### ISSUE TITLE
SCIM 2.0 API should support filtering

### ISSUE THREAD

**Issue by yurem** [GluuFederation/SCIM-Client#7]
SCIM 2.0 is based on: RFC7643 - SCIM: Core Schema and RFC7644 - SCIM: Protocol

According to section 3.4.2.2: https://tools.ietf.org/html/rfc7644#section-3.4.2.2 SCIM can provide filtering functionality.

**Comment by yurem** [comment]
Current our user search endpoint support search only by exact matching of one attribute.

**Comment by yurem** [comment]
Also it's not clear why there are 2 endpoints which do the same. The only returns different result:
- first result
- all results as list

As result first endpoint can return random result...

**Comment by uboznikov** [comment]
Opened new ticket in proper project:
https://github.com/GluuFederation/oxTrust/issues/212
